version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGithub2111Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: substractpackage
  gitServerName: srcCtrl_gitlab_Arti
  gitUrl: https://gitlab.com/ArtiKhareGitlabnew
  gitUsername: ArtiKhareGitlabnew
  gitBranch: master
services:
- serviceName: project.serengetigithub2111.integrations:gcd
  packages:
  - name: SerengetiGithub2111Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2099
